baseURL = "https://b3curv.github.io"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Adeline DOCHE"
theme = "dream"

disqusShortname = "Adeline DOCHE"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "#fff"
  backgroundImage = "/me/"
  linkColor = "seagreen"

  backgroundImageDark = "/me/background.jpg"
  darkLinkColor = "darkseagreen"

  images = ["me/"]

  author = "Adeline DOCHE"
  description = "blog de Adeline DOCHE"
  avatar = "/me/yy.JPG"
  headerTitle = "Adeline DOCHE"
  motto = "Bienvenu sur mon blog, tounez la page (bouton de deux cercles Ã  gauche) pour en savoir plus sur moi."

  rss = true

  instagram = "adeline_arts"
  linkedin = "adeline-doche-4707a91a1"
  github = "b3curv"

  siteStartYear = 2021

  favicon = "/favicon.ico"

  highlightjs = true
  highlightjsExtraLanguages = ["clojure", "ocaml"]
  highlightjsTheme = "tomorrow"
  highlightjsThemeDark = "tomorrow-night"

  enableSearch = true

  showSummaryCoverInPost = true

  [params.advanced]
    customCSS = ["css/custom.css"]
    customJS = []
